"""add complete candidate profile fields

Revision ID: 32bcdb0fe5de
Revises: 49de57290a8d
Create Date: 2026-09-13 22:17:24.596693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bcdb0fe5de'
down_revision: Union[str, Sequence[str], None] = '49de57290a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('email', sa.Text(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('phone', sa.Text(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('links', sa.JSON(), nullable=False))
    op.add_column('candidate_profiles', sa.Column('achievements', sa.JSON(), nullable=False))
    op.add_column('candidate_profiles', sa.Column('courses', sa.JSON(), nullable=False))
    op.add_column('candidate_profiles', sa.Column('preferred_employment_types', sa.JSON(), nullable=False))
    op.add_column('candidate_profiles', sa.Column('work_preferences', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'work_preferences')
    op.drop_column('candidate_profiles', 'preferred_employment_types')
    op.drop_column('candidate_profiles', 'courses')
    op.drop_column('candidate_profiles', 'achievements')
    op.drop_column('candidate_profiles', 'links')
    op.drop_column('candidate_profiles', 'phone')
    op.drop_column('candidate_profiles', 'email')
    # ### end Alembic commands ###
