"""add profile intelligence fields

Revision ID: 49de57290a8d
Revises: 7885ae6e2435
Create Date: 2026-09-13 15:04:32.260221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49de57290a8d'
down_revision: Union[str, Sequence[str], None] = '7885ae6e2435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "candidate_profiles",
        sa.Column("core_skills", sa.JSON(), nullable=True),
    )

    op.add_column(
        "candidate_profiles",
        sa.Column("supporting_skills", sa.JSON(), nullable=True),
    )

    op.add_column(
        "candidate_profiles",
        sa.Column("experience_level", sa.Text(), nullable=True),
    )

    op.add_column(
        "candidate_profiles",
        sa.Column("preferred_work_modes", sa.JSON(), nullable=True),
    )

    op.add_column(
        "candidate_profiles",
        sa.Column("career_keywords", sa.JSON(), nullable=True),
    )

    # Give existing profiles safe default values.
    op.execute(
        """
        UPDATE candidate_profiles
        SET core_skills = '[]'::json
        WHERE core_skills IS NULL
        """
    )

    op.execute(
        """
        UPDATE candidate_profiles
        SET supporting_skills = '[]'::json
        WHERE supporting_skills IS NULL
        """
    )

    op.execute(
        """
        UPDATE candidate_profiles
        SET preferred_work_modes = '[]'::json
        WHERE preferred_work_modes IS NULL
        """
    )

    op.execute(
        """
        UPDATE candidate_profiles
        SET career_keywords = '[]'::json
        WHERE career_keywords IS NULL
        """
    )

    op.execute(
        """
        UPDATE candidate_profiles
        SET experience_level = 'Entry Level'
        WHERE experience_level IS NULL
        """
    )

    # Now make JSON fields NOT NULL.
    op.alter_column(
        "candidate_profiles",
        "core_skills",
        nullable=False,
    )

    op.alter_column(
        "candidate_profiles",
        "supporting_skills",
        nullable=False,
    )

    op.alter_column(
        "candidate_profiles",
        "preferred_work_modes",
        nullable=False,
    )

    op.alter_column(
        "candidate_profiles",
        "career_keywords",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'career_keywords')
    op.drop_column('candidate_profiles', 'preferred_work_modes')
    op.drop_column('candidate_profiles', 'experience_level')
    op.drop_column('candidate_profiles', 'supporting_skills')
    op.drop_column('candidate_profiles', 'core_skills')
    # ### end Alembic commands ###
